from app.database import SessionLocal
from app.models.interview import InterviewQuestion
from app.models.scholarship import Scholarship
from datetime import date


def seed_data():
    db = SessionLocal()

    # Seed interview questions (25 flashcard + 15 quiz)
    if db.query(InterviewQuestion).count() == 0:
        questions = [
            # ========== ЕРӨНХИЙ (10 flashcard) ==========
            InterviewQuestion(
                question_mn="Өөрийнхөө тухай товч ярина уу",
                category="general",
                sample_answer="Боловсрол, туршлага, зорилгоо 1-2 минутад товч тайлбарлана. Хувийн амьдралын тухай биш, мэргэжлийн мэдээлэлд анхаарна. 'Elevator pitch' хэлбэрээр: хэн байна, юу хийдэг, юу сонирхдог, юуг хайж байна — гэсэн 4 асуултад хариулах.",
                advice="Урьдчилж толинд 30 секунд, 1 минут, 2 минутын хувилбар бэлдэж дадлагажих. Огт өөрийн тухай ерөнхий ярихгүй — ажилд шууд хамааралтай зүйл хэлэх.",
                difficulty="easy",
                tags="self-intro, warmup",
            ),
            InterviewQuestion(
                question_mn="Яагаад манай компанид ажиллахыг хүсэж байна вэ?",
                category="general",
                sample_answer="Компанийн зорилго, соёлтой таны ур чадвар хэрхэн нийцэж байгааг тайлбарлана. 'Надад цалин хэрэгтэй' гэж хариулахгүй — тодорхой шалтгаан: бүтээгдэхүүн, баг, өсөх боломж, чиглэл.",
                advice="Ярилцлагын өмнө компанийн сайт, сүүлийн мэдээ, LinkedIn-ий ажилчдыг судлаарай. Тодорхой 2-3 зүйл дурдаж чадвал гайхалтай.",
                difficulty="easy",
                tags="motivation, company-research",
            ),
            InterviewQuestion(
                question_mn="Таны хамгийн том давуу тал юу вэ?",
                category="general",
                sample_answer="Бодит жишээгээр давуу талаа тайлбарлана. Жишээ нь: 'Багаар ажиллах чадвартай — сүүлийн төслийнхөө үед 5 хүний багийг зохион байгуулж, хугацаанаас 2 долоо хоногийн өмнө дуусгасан.'",
                advice="Тодорхой жишээ заавал бэлдэх. Зүгээр 'хичээнгүй', 'хариуцлагатай' гэж хэлэхгүй — ажлын шаардлагатай уялдсан 1-2 давуу талаа жишээтэй ярих.",
                difficulty="easy",
                tags="strengths",
            ),
            InterviewQuestion(
                question_mn="Таны сул тал юу вэ?",
                category="general",
                sample_answer="Бодит сул талаа хэлж, түүнийг хэрхэн сайжруулж байгаагаа нэмнэ. Жишээ: 'Нийтийн өмнө илтгэх нь надад хэцүү байсан. Тиймээс сүүлийн 6 сар Toastmasters клубт оролцож, семинарын илтгэл хийдэг болсон.'",
                advice="Сул тал байхгүй гэж хэлэхгүй. Ажлын гол шаардлагад үл нийцэх сул тал хэлэхгүй (жишээ нь dev-д 'код бичих удаан').",
                difficulty="medium",
                tags="weaknesses",
            ),
            InterviewQuestion(
                question_mn="5 жилийн дараа өөрийгөө хаана харж байна вэ?",
                category="general",
                sample_answer="Тухайн салбарт өсөж хөгжих зорилгоо хэлнэ. Бодитой, ажлын байртай уялдсан байх. 'Junior developer → Senior → Team lead' гэх мэт мэргэжлийн замналыг тайлбарлах.",
                advice="Хэт ерөнхий 'амжилттай болох' гэж хэлэхгүй. Мөн 'өөрийн бизнес нээх' гэж хэлэх нь тухайн компанид үлдэнэ гэдэг итгэл өгөхгүй.",
                difficulty="medium",
                tags="career-goals",
            ),
            InterviewQuestion(
                question_mn="Яагаад таныг сонгох ёстой вэ?",
                category="general",
                sample_answer="Таны ур чадвар, туршлага тухайн ажилд хэрхэн тохирохыг тодорхой тайлбарлана. 'Би хариуцлагатай, идэвхтэй' гэхгүй, 'Өмнөх ажилд X төсөл хийж Y үр дүнд хүрсэн' гэх байдлаар баримттай.",
                advice="Job description-ийг уншиж, хамгийн чухал 3 шаардлагад таарах жишээгээ бэлтгэх.",
                difficulty="medium",
                tags="selling-yourself",
            ),
            InterviewQuestion(
                question_mn="Цалингийн хүлээлт тань хэд вэ?",
                category="general",
                sample_answer="Зах зээлийн судалгааны үндсэн дээр тодорхой хүрээ өгнө. Жишээ: 'Миний ур чадвар, туршлагад үндэслэн 2.5–3.5 сая төгрөг тохиромжтой гэж үзэж байна.' Компанийн бюджет, ажлын үүрэгт уян хатан хандах.",
                advice="Тодорхой тоо хүрээ өгөх. glassdoor.mn, worki.mn дээр ижил албан тушаалын цалинг судлах.",
                difficulty="hard",
                tags="salary",
            ),
            InterviewQuestion(
                question_mn="Яагаад өмнөх ажлаасаа гарсан/гарах гэж байна вэ?",
                category="general",
                sample_answer="Өсөлтийн шинэ боломж хайж байгаа, мэргэжлийн чиглэлээ өөрчлөх, шинэ сорилт хүсэж байгаагаа хэлнэ. Өмнөх ажил олгогчийг шүүмжлэхгүй.",
                advice="Ямар ч байсан өмнөх ажил, хамт ажиллагсдаа муугаар ярихгүй — энэ нь профессионал биш харагдана.",
                difficulty="medium",
                tags="job-change",
            ),
            InterviewQuestion(
                question_mn="Танд юу асуух уу?",
                category="general",
                sample_answer="3-5 асуулт бэлдэж ирэх. Жишээ нь: 'Энэ албан тушаал дээр амжилттай ажиллахын тулд юуг чухалчлах ёстой вэ?', 'Багийн соёл ямар вэ?', 'Эхний 3 сарын хүлээлт юу вэ?'",
                advice="Цалин, амралтын өдрийг эхний ярилцлагад асуухгүй. 'Надад асуух юм байхгүй' гэж хэзээ ч хэлэхгүй — сонирхолгүй мэт харагдана.",
                difficulty="easy",
                tags="your-questions",
            ),
            InterviewQuestion(
                question_mn="Бидэнтэй хамт ажиллах юу танд хамгийн тохиромжтой вэ?",
                category="general",
                sample_answer="Компанийн онцлог давуу талтай өөрийн хэрэгцээ, зорилгыг уялдуулан тайлбарлана. Жишээ: 'Танай баг remote-first соёлтой нь надад чухал, гэр бүлийн хажууд уян хатан ажиллах боломж олгоно.'",
                advice="Компанийн вэбсайтаас соёл, давуу тал судалж тодорхой дурдах.",
                difficulty="medium",
                tags="company-fit",
            ),

            # ========== ТЕХНИКИЙН FLASHCARD (8) ==========
            InterviewQuestion(
                question_mn="REST API гэж юу вэ? HTTP методуудыг нэрлэж тайлбарлана уу",
                category="technical",
                sample_answer="REST (Representational State Transfer) нь веб сервисийн архитектурын загвар. Үндсэн методууд: GET (унших), POST (шинээр үүсгэх), PUT (бүхэлд нь шинэчлэх), PATCH (хэсэгчилсэн шинэчлэл), DELETE (устгах). Resource-д URL-аар хандана (/api/users/1).",
                advice="Жишээ URL, request/response бичиж үзүүлэх. Stateless гэдэг ойлголтыг дурдах.",
                difficulty="medium",
                tags="web, backend, api",
            ),
            InterviewQuestion(
                question_mn="Git гэж юу вэ? Branch, merge, rebase ялгааг тайлбарла",
                category="technical",
                sample_answer="Git бол хувилбар удирдлагын систем. Branch нь кодын бие даасан салбар — feature бүрийг тусад нь хөгжүүлэхэд ашиглана. Merge — хоёр салбарыг нэгтгэх, merge commit үүсгэнэ. Rebase — branch-ийн commit-уудыг өөр base дээр шилжүүлэх, түүхийг цэвэрхэн хадгалах.",
                advice="Pull request, conflict resolution туршлага дурдах.",
                difficulty="medium",
                tags="git, version-control",
            ),
            InterviewQuestion(
                question_mn="SQL ба NoSQL өгөгдлийн сангийн ялгаа, хэзээ аль нэгийг сонгох вэ?",
                category="technical",
                sample_answer="SQL (PostgreSQL, MySQL): бүтэцтэй, хүснэгт суурилсан, ACID баталгаа, сайн normalize хийсэн өгөгдөлд тохиромжтой. NoSQL (MongoDB, Redis): уян хатан schema, хэвтээ scale, document/key-value загвар. Transactional өгөгдөлд SQL, real-time analytics/caching-д NoSQL.",
                advice="Тодорхой хэрэглээний жишээ өгөх (банкны гүйлгээ → SQL, chat message → NoSQL).",
                difficulty="hard",
                tags="database, architecture",
            ),
            InterviewQuestion(
                question_mn="OOP-ийн дөрвөн үндсэн зарчмыг тайлбарлана уу",
                category="technical",
                sample_answer="1) Encapsulation — өгөгдөл, түүнд үйлдэл хийх функцийг нэг class-д багцлах. 2) Inheritance — class нь өөр class-аас property/method өвлөх. 3) Polymorphism — нэг interface-д олон төрлийн implementation. 4) Abstraction — зөвхөн хэрэгцээт хэсгийг харуулж, нарийн ширийнийг нуух.",
                advice="Код дээр жишээ өгч чадвал маш сайн.",
                difficulty="medium",
                tags="oop, programming",
            ),
            InterviewQuestion(
                question_mn="JavaScript-ийн var, let, const ялгаа юу вэ?",
                category="technical",
                sample_answer="var: function-scoped, hoisted (undefined гэж), дахин зарлаж болно. let: block-scoped, hoisted ч temporal dead zone, дахин зарлаж болохгүй ч утгыг өөрчилж болно. const: block-scoped, анхдагч утга өгөх шаардлагатай, дахин зарлах/утгыг сольж болохгүй.",
                advice="Code жишээгээр hoisting болон scope-ыг харуулах.",
                difficulty="medium",
                tags="javascript, frontend",
            ),
            InterviewQuestion(
                question_mn="React-ийн useState болон useEffect hook-ийн ялгаа юу вэ?",
                category="technical",
                sample_answer="useState — component дотор local state удирдах ([value, setValue] pair буцаана). useEffect — side effect-үүд хийх (API дуудах, subscription, DOM өөрчлөлт). useEffect нь render-ийн дараа ажиллана, dependency array-аар хэзээ дахин ажиллах нь удирдагдана.",
                advice="Жишээ код бичиж харуулах, cleanup function-ийн хэрэглээг дурдах.",
                difficulty="medium",
                tags="react, frontend",
            ),
            InterviewQuestion(
                question_mn="HTTP болон HTTPS ялгаа, TLS юу хийдэг вэ?",
                category="technical",
                sample_answer="HTTP нь шифрлэгдээгүй, HTTPS нь TLS/SSL шифрлэлттэй. TLS: 1) client-server хооронд аюулгүй handshake, 2) тэгш хэмт түлхүүр солилцох, 3) дамжиж буй өгөгдлийг шифрлэх.",
                advice="Certificate authority, handshake процессыг нэмж тайлбарлах.",
                difficulty="hard",
                tags="security, web",
            ),
            InterviewQuestion(
                question_mn="Frontend-д state management сан (Redux, Zustand) яагаад хэрэгтэй вэ?",
                category="technical",
                sample_answer="Том аппликешн дээр олон component хооронд state хуваалцах шаардлагатай. Prop drilling нь засвар үйлчилгээг хэцүү болгодог. Redux/Zustand нь global store үүсгэж, аль ч component-аас state унших/өөрчлөх боломжийг өгнө.",
                advice="Жижиг төсөлд context API хангалттай гэдгийг нэмэх.",
                difficulty="hard",
                tags="react, state-management",
            ),

            # ========== ЗАН ҮЙЛИЙН (7 STAR-д тохиромжтой) ==========
            InterviewQuestion(
                question_mn="Багаар ажиллаж амжилтанд хүрсэн туршлагаа ярина уу",
                category="behavioral",
                sample_answer="S(Situation) — ямар нөхцөлд, T(Task) — ямар үүрэг, A(Action) — юу хийсэн, R(Result) — ямар үр дүн. Жишээ: '3-р курст бүлгийн төсөл хийхэд (S), би Git workflow тохируулах үүрэгтэй байсан (T). 4 хүнд зориулж branch strategy, code review процесс бий болгосон (A). Үр дүнд код зөрчилдөөн 80% буурч, төслөө 2 долоо хоногийн өмнө дуусгасан (R).'",
                advice="Заавал тоон үр дүн оруулах (хэмжих боломжтой).",
                difficulty="medium",
                tags="star, teamwork",
            ),
            InterviewQuestion(
                question_mn="Хүнд хэцүү шийдвэр гаргасан туршлагаа ярина уу",
                category="behavioral",
                sample_answer="Тодорхой жишээ сонгож STAR бүтэцтэй ярих. Жишээ: хоёр сайн сонголтын аль нэгийг шалгах, багийн гишүүний алдааг хэлэх, deadline-ийг өөрчлөхөөр шаардах гэх мэт. Ямар хүчин зүйлсийг харгалзсан, хэрхэн шийдсэн, үр дүн юу байсныг тайлбарлана.",
                advice="Үнэн зөв, шийдвэрлэхэд хэцүү жишээ сонгох. Тайлан бичих, бусдаас зөвлөгөө авах зэрэг арга зам дурдах.",
                difficulty="hard",
                tags="star, decision-making",
            ),
            InterviewQuestion(
                question_mn="Алдаанаасаа сургамж авсан туршлагаа ярина уу",
                category="behavioral",
                sample_answer="Алдаагаа хүлээн зөвшөөрч, юу сурсан, цаашид хэрхэн сайжирсныг хэлнэ. Жишээ: 'Нэгэн удаа тестгүйгээр production-д шууд deploy хийж bug үүсгэсэн. Ингэснээр CI/CD-д заавал тест нэмж ажиллуулдаг процесс сурсан. Одоо ямар ч өөрчлөлтөд тестийг урьтал болгодог.'",
                advice="Алдааг нууцлахгүй, харин юу сурснаа анхаарах. 'Perfectionist-ийн төлөө' гэж хуурамч алдаа хэлэхгүй.",
                difficulty="medium",
                tags="star, growth-mindset",
            ),
            InterviewQuestion(
                question_mn="Стресстэй нөхцөлд хэрхэн ажилладаг вэ?",
                category="behavioral",
                sample_answer="Тодорхой жишээ сонгож STAR хариулна. 'Deadline 2 өдрийн өмнө өөрчлөгдсөн үед (S), зорилт эрэмблэх шаардлагатай байсан (T). Ажлыг critical vs nice-to-have гэж хувааж, өдөр бүрийн milestone тогтоосон (A). Хугацаандаа дуусгасан бөгөөд багт эерэг уур амьсгал үлдсэн (R).'",
                advice="Нойргүй хоноод бүтсэн гэхгүй — удирдлагын сайн арга зам харуулах.",
                difficulty="medium",
                tags="star, stress-management",
            ),
            InterviewQuestion(
                question_mn="Багийн гишүүнтэй зөрчилдөөн үүссэн тохиолдлыг ярина уу",
                category="behavioral",
                sample_answer="Эерэг, бүтээмжтэй шийдсэн жишээ. 'Кодын стандарт талаар санал зөрөгдсөн (S). Багийн үр ашгийг хадгалах шаардлагатай байсан (T). 1-1 уулзалт хийж, хоёулангийн санааг сонсож, компромис гаргасан (A). Үр дүнд ажил үргэлжилсэн бөгөөд баг улам бэхжсэн (R).'",
                advice="Хүнийг буруутгах ярилтлгүй, процессоор шийдсэн байдлыг харуулах.",
                difficulty="hard",
                tags="star, conflict-resolution",
            ),
            InterviewQuestion(
                question_mn="Удирдлага тань шаардсан зүйлд эсэргүүцсэн туршлага?",
                category="behavioral",
                sample_answer="Профессионал зан чанар харуулсан жишээ. 'Чанар муутай код-ыг хурдан release-лэхийг шаардсан (S). Urgent боловч цаашдын асуудал үүсэх эрсдэлтэй байсан (T). Боломжит эрсдэлийг баримттайгаар танилцуулж, alternative хувилбар санал болгосон (A). Удирдлага хүлээн авч, 3 хоногийн дараа бүрэн release хийсэн (R).'",
                advice="Буруу шалтгаанаар эсэргүүцсэн гэхгүй, шалтгаантай, шийдэлтэй байдлыг харуулах.",
                difficulty="hard",
                tags="star, upward-management",
            ),
            InterviewQuestion(
                question_mn="Хэзээ нэгэн цагт санал болгоогүй үүрэг хариуцсан туршлага?",
                category="behavioral",
                sample_answer="Санаачлагатай байсан жишээ. 'Өмнөх ажлын бүх документ хуучирсан (S). Албан үүрэг минь биш ч багийн үр ашгийг сайжруулахыг хүссэн (T). 2 долоо хоногт Confluence дээр онбординг гарын авлага бичсэн (A). Шинэ ажилтны онбординг хугацаа 2 долоо хоногоос 4 өдөр болж буурсан (R).'",
                advice="Өөрийн зорилгоо ялгаруулж биш, багийн үр ашиг дээр анхаарах.",
                difficulty="medium",
                tags="star, initiative",
            ),

            # ========== QUIZ АСУУЛТ (15) ==========
            # --- Техникийн quiz (10) ---
            InterviewQuestion(
                question_mn="HTTP статус код 404 юуг илэрхийлдэг вэ?",
                category="technical",
                is_quiz=True,
                option_a="Серверийн дотоод алдаа",
                option_b="Хандалт хориотой",
                option_c="Хүссэн resource олдсонгүй",
                option_d="Хүсэлт амжилттай",
                correct_option="c",
                explanation="404 Not Found — хэрэглэгчийн хүссэн resource (page, file г.м.) сервер дээр олдсонгүй гэсэн үг. 500 — сервер алдаа, 403 — хориотой, 200 — амжилттай.",
                difficulty="easy",
                tags="http, web",
            ),
            InterviewQuestion(
                question_mn="Дараах өгөгдлийн сангаас аль нь NoSQL вэ?",
                category="technical",
                is_quiz=True,
                option_a="PostgreSQL",
                option_b="MongoDB",
                option_c="MySQL",
                option_d="Oracle",
                correct_option="b",
                explanation="MongoDB нь document-based NoSQL өгөгдлийн сан. PostgreSQL, MySQL, Oracle бүгд relational (SQL) өгөгдлийн сан.",
                difficulty="easy",
                tags="database",
            ),
            InterviewQuestion(
                question_mn="Git-д хамгийн сүүлийн commit-ийг буцаах тушаал аль нь вэ?",
                category="technical",
                is_quiz=True,
                option_a="git undo",
                option_b="git revert HEAD",
                option_c="git remove last",
                option_d="git delete",
                correct_option="b",
                explanation="git revert HEAD — хамгийн сүүлийн commit-ийн эсрэг шинэ commit үүсгэж буцаана (түүхийг хадгалсан). git reset --hard HEAD~1 нь түүхээс устгана.",
                difficulty="medium",
                tags="git",
            ),
            InterviewQuestion(
                question_mn="JavaScript-д аль нь primitive data type биш вэ?",
                category="technical",
                is_quiz=True,
                option_a="string",
                option_b="number",
                option_c="object",
                option_d="boolean",
                correct_option="c",
                explanation="object нь reference type. JavaScript-ийн primitive төрлүүд: string, number, boolean, null, undefined, symbol, bigint.",
                difficulty="easy",
                tags="javascript",
            ),
            InterviewQuestion(
                question_mn="React-д component-ийн state өөрчлөгдөх үед юу болдог вэ?",
                category="technical",
                is_quiz=True,
                option_a="Хуудас бүхэлдээ дахин ачаалагдана",
                option_b="Component дахин render хийгдэнэ",
                option_c="State шинэчлэгдэхгүй",
                option_d="Алдаа гарна",
                correct_option="b",
                explanation="React-д state өөрчлөгдвөл тухайн component болон түүний children дахин render хийгдэнэ (виртуал DOM дифф хийсний дараа шаардлагатай хэсгийг DOM-д update-дана).",
                difficulty="medium",
                tags="react",
            ),
            InterviewQuestion(
                question_mn="SQL-д мөр устгах тушаал аль нь вэ?",
                category="technical",
                is_quiz=True,
                option_a="REMOVE FROM users WHERE id=1",
                option_b="DELETE FROM users WHERE id=1",
                option_c="DROP FROM users WHERE id=1",
                option_d="ERASE FROM users WHERE id=1",
                correct_option="b",
                explanation="DELETE FROM table WHERE condition — мөр устгана. DROP TABLE бүхэл хүснэгтийг устгана. REMOVE, ERASE нь SQL command биш.",
                difficulty="easy",
                tags="sql, database",
            ),
            InterviewQuestion(
                question_mn="Нууц үгийг өгөгдлийн санд хэрхэн хадгалах нь зөв вэ?",
                category="technical",
                is_quiz=True,
                option_a="Plain text-ээр",
                option_b="Base64-ээр encode хийж",
                option_c="Bcrypt-ээр hash хийж",
                option_d="Reverse хийж",
                correct_option="c",
                explanation="Bcrypt, Argon2 зэрэг one-way hash алгоритмоор хадгална. Plain text-ээр хадгалах хэзээ ч болохгүй, Base64 нь encoding (буцаан read хийгдэх) тул аюулгүй биш.",
                difficulty="medium",
                tags="security",
            ),
            InterviewQuestion(
                question_mn="JWT token ямар форматтай байдаг вэ?",
                category="technical",
                is_quiz=True,
                option_a="XML тэгт",
                option_b="3 хэсгээс бүрдсэн, .-ээр зааглагдсан (header.payload.signature)",
                option_c="Binary файл",
                option_d="Зөвхөн тоо",
                correct_option="b",
                explanation="JWT = JSON Web Token. Дараах бүтэцтэй: header.payload.signature, тус бүр base64url encode-логдсон JSON. Signature нь toсtampering хамгаалалт.",
                difficulty="medium",
                tags="security, auth",
            ),
            InterviewQuestion(
                question_mn="Python-д list болон tuple-ийн гол ялгаа юу вэ?",
                category="technical",
                is_quiz=True,
                option_a="Хоёр нь ялгаагүй",
                option_b="List нь mutable, tuple нь immutable",
                option_c="Tuple илүү хурдан биш",
                option_d="List зөвхөн тоо хадгална",
                correct_option="b",
                explanation="List — өөрчилж (mutable) болно, []. Tuple — өөрчлөх боломжгүй (immutable), (). Tuple хурдан, санах ойд бага эзэлнэ.",
                difficulty="easy",
                tags="python",
            ),
            InterviewQuestion(
                question_mn="CSS-д хамгийн өндөр priority-той аль нь вэ?",
                category="technical",
                is_quiz=True,
                option_a="Class selector",
                option_b="ID selector",
                option_c="!important",
                option_d="Inline style",
                correct_option="c",
                explanation="!important нь CSS-ийн хамгийн өндөр priority. Priority дараалал: inline > ID > class > tag. Гэвч !important бүгдийг давна.",
                difficulty="medium",
                tags="css, frontend",
            ),

            # --- Ерөнхий quiz (5) ---
            InterviewQuestion(
                question_mn="Ярилцлагад хамгийн чухал юу вэ?",
                category="general",
                is_quiz=True,
                option_a="Үнэтэй хувцас өмсөх",
                option_b="Өөрийгөө мэдрэх, компанийг судалж бэлдэх",
                option_c="Асуулт бүрд маш удаан хариулах",
                option_d="Өмнөх ажлаа шүүмжлэх",
                correct_option="b",
                explanation="Өөрийн давуу сул талыг мэдэж, компанийн тухай судалж, яагаад тэнд ажиллахыг хүсч буйгаа тодорхой болгох нь ярилцлагын амжилтын үндэс.",
                difficulty="easy",
                tags="interview-basics",
            ),
            InterviewQuestion(
                question_mn="'Таны сул тал юу вэ?' асуултад хэрхэн хариулах нь зөв вэ?",
                category="general",
                is_quiz=True,
                option_a="Сул тал байхгүй гэх",
                option_b="Ажилд огт нөлөөлдөггүй хамаагүй сул тал нэрлэх",
                option_c="Бодит сул тал + түүнийг хэрхэн сайжруулж буйгаа хэлэх",
                option_d="Perfectionist байдгаа хэлэх",
                correct_option="c",
                explanation="Ярилцлага авагч таны өөрийгөө үнэлэх чадвар, хөгжүүлэх сэтгэлгээг хардаг. Бодит сул тал хэлж, яаж сайжруулж буйгаа нэмэх нь зөв. 'Perfectionist' нь хэт ашиглагдсан clichéд тооцогддог.",
                difficulty="medium",
                tags="weaknesses",
            ),
            InterviewQuestion(
                question_mn="Ярилцлагад орохоос өмнө хэр өмнө компани дээр очих нь зөв вэ?",
                category="general",
                is_quiz=True,
                option_a="Яг хугацаандаа",
                option_b="30 минутын өмнө",
                option_c="10-15 минутын өмнө",
                option_d="1 цагийн өмнө",
                correct_option="c",
                explanation="10-15 минутын өмнө ирэх нь хамгийн тохиромжтой. Хэт эрт ирэх нь ярилцлага авагчийг айж дарамталдаг, хэт оройтох нь буруу сэтгэгдэл төрүүлнэ.",
                difficulty="easy",
                tags="interview-basics",
            ),
            InterviewQuestion(
                question_mn="Ярилцлагын төгсгөлд 'Танд юу асуух уу?' гэхэд хэрхэн хариулах вэ?",
                category="general",
                is_quiz=True,
                option_a="'Байхгүй' гэж хэлэх",
                option_b="Цалингийн тухай шууд асуух",
                option_c="Компани, албан тушаал, багийн тухай бодолтой асуулт асуух",
                option_d="Хувийн амьдралын тухай асуух",
                correct_option="c",
                explanation="Энэ нь таны сонирхол, бэлтгэлийг харуулах боломж. 'Эхний 3 сарын амжилтын шалгуур юу вэ?', 'Багийн соёл ямар вэ?' гэх бодолтой асуулт асуух нь зүйтэй.",
                difficulty="medium",
                tags="your-questions",
            ),
            InterviewQuestion(
                question_mn="Онлайн ярилцлагад хамгийн чухал техник бэлтгэл аль нь вэ?",
                category="general",
                is_quiz=True,
                option_a="Шинэ камер худалдаж авах",
                option_b="Интернэт, камер, микрофон, арын орчин шалгах",
                option_c="Үнэтэй наушник худалдаж авах",
                option_d="Зөвхөн камераа шалгах",
                correct_option="b",
                explanation="Онлайн ярилцлагад интернэтийн холболт, камерын чанар, микрофоны дуу, арын орчин (цэвэрхэн, сайн гэрэлтэй) бүгдийг урьдчилан шалгаж, 1 өдрийн өмнө туршилт хийх нь чухал.",
                difficulty="easy",
                tags="online-interview",
            ),
        ]

        db.add_all(questions)
        db.commit()
        print(f"✓ Seeded {len(questions)} interview questions ({sum(1 for q in questions if q.is_quiz)} quiz)")

    # Seed scholarships (only if empty)
    if db.query(Scholarship).count() == 0:
        scholarships = [
            Scholarship(name="Монголын Хөгжлийн Банкны тэтгэлэг", organization="Хөгжлийн банк", target="Бакалавр", requirements="GPA 3.0+, санхүүгийн хэрэгцээ", deadline=date(2026, 6, 30), website_url="https://mdb.mn", description="Санхүүгийн салбарын оюутнуудад зориулсан"),
            Scholarship(name="Голомт банкны тэтгэлэг", organization="Голомт банк", target="Бакалавр", requirements="GPA 3.2+, идэвхтэй оролцоо", deadline=date(2026, 5, 15), website_url="https://golomtbank.com", description="Бизнесийн чиглэлийн оюутнуудад"),
            Scholarship(name="МУИС-ийн Ректорын тэтгэлэг", organization="МУИС", target="Бакалавр", requirements="GPA 3.5+", deadline=date(2026, 9, 1), website_url="https://num.edu.mn", description="Сурлагын амжилт өндөртэй оюутнуудад"),
            Scholarship(name="ШУТИС-ийн тэтгэлэг", organization="ШУТИС", target="Бакалавр", requirements="GPA 3.0+, инженерийн чиглэл", deadline=date(2026, 8, 15), website_url="https://must.edu.mn", description="Инженерийн чиглэлийн оюутнуудад"),
            Scholarship(name="Оюу толгой тэтгэлэг", organization="Оюу толгой", target="Бакалавр", requirements="Уул уурхайн чиглэл, GPA 3.0+", deadline=date(2026, 4, 30), website_url="https://ot.mn", description="Уул уурхайн салбарын оюутнуудад"),
            Scholarship(name="MCS группын тэтгэлэг", organization="MCS Group", target="Бакалавр", requirements="Бизнесийн удирдлага, маркетинг", deadline=date(2026, 7, 1), website_url="https://mcs.mn", description="Бизнесийн чиглэлийн оюутнуудад"),
        ]
        db.add_all(scholarships)
        db.commit()
        print(f"✓ Seeded {len(scholarships)} scholarships")

    db.close()